-- Create chimera_story_compiled_ruleset table
-- Phase 3: Compiler - snapshot story's rules into a single JSON object

BEGIN;

-- Create compiled ruleset table
CREATE TABLE IF NOT EXISTS public.chimera_story_compiled_ruleset (
    story_id text PRIMARY KEY REFERENCES public.chimera_stories(id) ON DELETE CASCADE,
    compiled_json jsonb NOT NULL DEFAULT '{}',
    source_manifest jsonb NOT NULL DEFAULT '[]',
    last_compiled_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_chimera_story_compiled_ruleset_story_id UNIQUE (story_id)
);

-- Create index for compiled_at queries
CREATE INDEX IF NOT EXISTS idx_chimera_story_compiled_ruleset_last_compiled_at 
  ON public.chimera_story_compiled_ruleset(last_compiled_at);

-- Add comments for documentation
COMMENT ON TABLE public.chimera_story_compiled_ruleset IS 
  'Compiled ruleset snapshots for Chimera V2 stories. Generated by the compiler from linked ruleset templates.';
COMMENT ON COLUMN public.chimera_story_compiled_ruleset.story_id IS 
  'Foreign key to chimera_stories.id. One compiled ruleset per story.';
COMMENT ON COLUMN public.chimera_story_compiled_ruleset.compiled_json IS 
  'The final, merged ruleset object containing all rules from Main System, Subsystems, World Modifiers, and Story Modifiers.';
COMMENT ON COLUMN public.chimera_story_compiled_ruleset.source_manifest IS 
  'JSON array containing the "receipt" of template IDs and versions used in the compilation. Format: [{"id": "...", "version": 1}, ...]';
COMMENT ON COLUMN public.chimera_story_compiled_ruleset.last_compiled_at IS 
  'Timestamp of when the compiled ruleset was last generated.';

COMMIT;

