name = "stonecaster-redirects"
main = "workers/redirects.js"
compatibility_date = "2024-01-01"

# Route configuration for redirects
# This should be deployed to handle redirects before the main app
[[routes]]
pattern = "stonecaster.com/adventures*"
zone_name = "stonecaster.com"

# Environment variables
[vars]
ENVIRONMENT = "production"