name = "stonecaster-og"
main = "workers/og.ts"
compatibility_date = "2023-10-01"

[routes]
pattern = "/og/*"
zone_name = "${PUBLIC_SITE_DOMAIN}"

# Environment variables
[vars]
ENVIRONMENT = "production"