name = "stonecaster-frontend"
main = "dist/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[routes]]
pattern = "/*"
custom_domain = true

[env.production]
name = "stonecaster-frontend"
