app = "stonecaster-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[[checks]]
  name = "http"
  type = "http"
  interval = "10s"
  timeout = "2s"
  grace_period = "10s"
  path = "/health"
  method = "get"
  port = 8080