// [CHIMERA V3] Architecture: Greenfield | Layer: Frontend
/**
 * Rulesets Management Page
 * Dashboard page for managing Chimera rulesets
 */

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Plus, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { getRulesets, createRuleset } from '@/services/chimera-api';
import type { RulesetDefinition } from '@shared/types/chimera-authoring';

const UI_CATEGORY_COLORS = {
  foundation: 'default',
  expansion: 'secondary',
  flavor: 'outline',
} as const;

export default function RulesetsPage() {
  const queryClient = useQueryClient();
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    ui_category: 'foundation' as 'foundation' | 'expansion' | 'flavor',
    exclusion_group: '',
  });

  const { data: rulesets, isLoading, error } = useQuery({
    queryKey: ['chimera-rulesets'],
    queryFn: () => getRulesets(),
    staleTime: 30 * 1000,
  });

  const createMutation = useMutation({
    mutationFn: async (data: RulesetDefinition) => {
      return await createRuleset(data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['chimera-rulesets'] });
      setIsCreateDialogOpen(false);
      setFormData({ name: '', ui_category: 'foundation', exclusion_group: '' });
      toast.success('Ruleset created successfully');
    },
    onError: (error: Error) => {
      toast.error(error.message || 'Failed to create ruleset');
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    const rulesetData: RulesetDefinition = {
      id: '', // Will be generated by backend
      name: formData.name,
      ui_category: formData.ui_category,
      exclusion_group: formData.exclusion_group || null,
      dependencies: [],
      provides_tags: [],
      state_contributions: {},
      actions: {},
      ai_instructions: {},
    };

    createMutation.mutate(rulesetData);
  };

  if (isLoading) {
    return (
      <div className="container mx-auto px-4 py-8 max-w-6xl">
        <div className="flex items-center justify-center min-h-[400px]">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="container mx-auto px-4 py-8 max-w-6xl">
        <Card>
          <CardHeader>
            <CardTitle>Error</CardTitle>
            <CardDescription>
              {error instanceof Error ? error.message : 'Failed to load rulesets'}
            </CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8 max-w-6xl">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold">Rulesets</h1>
          <p className="text-muted-foreground mt-1">
            Manage game rulesets and mechanics
          </p>
        </div>
        <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="h-4 w-4 mr-2" />
              Create Ruleset
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Create New Ruleset</DialogTitle>
              <DialogDescription>
                Define a new ruleset for your game system
              </DialogDescription>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name">Name</Label>
                <Input
                  id="name"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="ui_category">UI Category</Label>
                <Select
                  value={formData.ui_category}
                  onValueChange={(value) =>
                    setFormData({ ...formData, ui_category: value as 'foundation' | 'expansion' | 'flavor' })
                  }
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="foundation">Foundation</SelectItem>
                    <SelectItem value="expansion">Expansion</SelectItem>
                    <SelectItem value="flavor">Flavor</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="exclusion_group">Exclusion Group (optional)</Label>
                <Input
                  id="exclusion_group"
                  value={formData.exclusion_group}
                  onChange={(e) => setFormData({ ...formData, exclusion_group: e.target.value })}
                  placeholder="e.g., combat-system"
                />
              </div>
              <div className="flex justify-end gap-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setIsCreateDialogOpen(false)}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={createMutation.isPending}>
                  {createMutation.isPending && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
                  Create
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>All Rulesets</CardTitle>
          <CardDescription>
            {rulesets?.length || 0} ruleset{rulesets?.length !== 1 ? 's' : ''} total
          </CardDescription>
        </CardHeader>
        <CardContent>
          {rulesets && rulesets.length > 0 ? (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Name</TableHead>
                  <TableHead>UI Category</TableHead>
                  <TableHead>Exclusion Group</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {rulesets.map((ruleset) => (
                  <TableRow key={ruleset.id}>
                    <TableCell className="font-medium">{ruleset.name}</TableCell>
                    <TableCell>
                      <Badge variant={UI_CATEGORY_COLORS[ruleset.ui_category]}>
                        {ruleset.ui_category}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      {ruleset.exclusion_group ? (
                        <Badge variant="outline">{ruleset.exclusion_group}</Badge>
                      ) : (
                        <span className="text-muted-foreground">—</span>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              No rulesets found. Create your first ruleset to get started.
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

