/**
 * Chimera Runtime Types
 * Defines the structure for runtime game state and communication DTOs
 */

import { z } from 'zod';

/**
 * GameState
 * The complete state of a game session, split into mechanical and narrative tiers
 */
export const GameStateSchema = z.object({
  /**
   * Tier 1 (Mechanical/Strict) state
   * Contains deterministic, rule-bound state (HP, Inventory, Time, Stats)
   * Changes are computed by the Engine and must be consistent and verifiable
   */
  tier1_mechanical: z.record(z.unknown()).default({}),

  /**
   * Tier 0 (Narrative/Flexible) state
   * Contains flexible, narrative-driven state (Memories, Relationships, Story Flags)
   * Changes are generated by MAS2 and can be more interpretive and contextual
   */
  tier0_narrative: z.record(z.unknown()).default({}),
});

export type GameState = z.infer<typeof GameStateSchema>;

/**
 * Mas1ResponseDto
 * Response from MAS1 (Interpreter) after parsing player input
 */
export const Mas1ResponseDtoSchema = z.object({
  /**
   * Action slug identifying the requested action
   */
  action_slug: z.string(),

  /**
   * Parameters extracted from player input for the action
   */
  parameters: z.record(z.unknown()),

  /**
   * Sentiment or emotional tone detected in the player input
   */
  sentiment: z.string(),
});

export type Mas1ResponseDto = z.infer<typeof Mas1ResponseDtoSchema>;

/**
 * EngineResultDto
 * Result from the Engine (Deterministic Resolver) after processing an action
 */
export const EngineResultDtoSchema = z.object({
  /**
   * Whether the action was successfully processed
   */
  success: z.boolean(),

  /**
   * Numeric deltas applied to state (e.g., HP: -5, Gold: +10)
   */
  numeric_deltas: z.record(z.string(), z.number()).default({}),

  /**
   * Human-readable summary of the outcome
   */
  outcome_summary: z.string(),
});

export type EngineResultDto = z.infer<typeof EngineResultDtoSchema>;

/**
 * Mas2ResponseDto
 * Response from MAS2 (Narrator) after generating narrative
 */
export const Mas2ResponseDtoSchema = z.object({
  /**
   * Ripple narrative - the narrative text describing what happened
   */
  ripple_narrative: z.string(),

  /**
   * Tier 0 mutations - changes to narrative state (memories, relationships, etc.)
   */
  tier0_mutations: z.record(z.string(), z.unknown()).default({}),
});

export type Mas2ResponseDto = z.infer<typeof Mas2ResponseDtoSchema>;

