/**
 * @swagger
 * tags:
 *   - name: Chimera V2 Entities
 *     description: User-facing CRUD endpoints for Chimera entity templates
 */

import { Router, type Request, type Response } from "express";
import { z } from "zod";
import { requireAuth, requireAdmin } from "../middleware/auth.unified.js";
import { validateRequest } from "../middleware/validation.js";
import { sendSuccess, sendErrorWithStatus } from "../utils/response.js";
import { ApiErrorCode } from "@shared";
import { supabaseAdmin } from "../services/supabase.js";

import { ChimeraEntitiesService } from "../services/chimera/chimera-entities.service.js";

import { EntityContentReadService } from "../services/content/entity-content-read.service.js";
import {
  EntityReadQuerySchema,
  EntityReadIdSchema,
} from "../../../shared/src/types/chimera-entity-read.js";
import { ServiceError } from "../utils/serviceError.js";
import { sendError, getTraceId } from "../utils/response.js";

const router = Router();

async function entityRead(
  req: Request,
  res: Response,
  action: (service: EntityContentReadService) => Promise<unknown>,
): Promise<void> {
  try {
    sendSuccess(
      res,
      await action(EntityContentReadService.forRequest(req, getTraceId(req))),
      req,
    );
  } catch (error) {
    if (error instanceof ServiceError)
      return sendError(
        res,
        error.error.code,
        error.error.message,
        req,
        error.statusCode,
      );
    if (error instanceof z.ZodError)
      return sendError(
        res,
        ApiErrorCode.VALIDATION_FAILED,
        "Invalid entity read request",
        req,
        422,
      );
    console.error(
      JSON.stringify({
        level: "error",
        event: "entity_read_route_failed",
        traceId: getTraceId(req),
      }),
    );
    sendError(
      res,
      ApiErrorCode.INTERNAL_ERROR,
      "Entity content is temporarily unavailable.",
      req,
      503,
    );
  }
}

// Schema for UUID entity ID
const EntityIdParamSchema = z.object({
  id: z.string().uuid(),
});

// All routes require authentication
router.use(requireAuth);

// Zod schemas for validation
const EntityTypeSchema = z.enum([
  "NPC",
  "ITEM",
  "FACTION",
  "LOCATION",
  "PLAYER",
]);
const VisibilitySchema = z.enum(["private", "pending_approval", "public"]);

const CreateEntitySchema = z.object({
  display_name: z.string().min(1).max(200),
  description_short: z.string().max(500).optional().nullable(),
  description_long: z.string().optional().nullable(),
  entity_type: EntityTypeSchema,
  archetype_handle: z.string().optional().nullable(),
  base_state_json: z.record(z.unknown()).default({}),
  raw_data: z.record(z.unknown()).optional(),
  tags: z.array(z.string()).default([]),
  world_id: z.string().uuid().optional().nullable(),
  images: z
    .array(
      z.object({
        id: z.string().optional(),
        url: z.string(),
        role: z.string().optional(),
        label: z.string().optional(),
      }),
    )
    .optional()
    .default([]),
});

const UpdateEntitySchema = z
  .object({
    display_name: z.string().min(1).max(200).optional(),
    description_short: z.string().max(500).optional().nullable(),
    description_long: z.string().optional().nullable(),
    entity_type: EntityTypeSchema.optional(),
    archetype_handle: z.string().optional().nullable(),
    base_state_json: z.record(z.unknown()).optional(),
    raw_data: z.record(z.unknown()).optional(),
    tags: z.array(z.string()).optional(),
    world_id: z.string().uuid().optional().nullable(),
    visibility: VisibilitySchema.optional(),
    images: z
      .array(
        z.object({
          id: z.string().optional(),
          url: z.string(),
          role: z.string().optional(),
          label: z.string().optional(),
        }),
      )
      .optional(),
  })
  .transform((data) => {
    // Remove empty string values - convert to undefined so they're omitted
    const cleaned: any = { ...data };
    if (cleaned.entity_type === "" || cleaned.entity_type === null) {
      delete cleaned.entity_type;
    }
    if (cleaned.display_name === "" || cleaned.display_name === null) {
      delete cleaned.display_name;
    }
    return cleaned;
  });

// Helper function to normalize tag names
function normalizeTagName(tagName: string): string {
  return tagName
    .trim()
    .toUpperCase()
    .replace(/\s+/g, "_")
    .replace(/[^A-Z0-9_]/g, "");
}

// Note: Entity IDs are now UUIDs generated by the database (gen_random_uuid())
// No need for a generateId function - the database will generate UUIDs automatically

/**
 * GET /api/v2/chimera/entities/selectable
 * listLibrary: Get all entities available to the user (for Casting Circle)
 *
 * Pattern: Shows user's items + system items + other users' public items
 * Unified query: owner_user_id = userId OR visibility = 'public'
 */
router.get("/selectable", (req: Request, res: Response) =>
  entityRead(req, res, (service) =>
    service.list(EntityReadQuerySchema.parse(req.query)),
  ),
);

/**
 * GET /api/v2/chimera/entities
 * Get all entities owned by the current user
 */
router.get("/", (req: Request, res: Response) =>
  entityRead(req, res, (service) =>
    service.list(EntityReadQuerySchema.parse(req.query), "rawOwned"),
  ),
);

/**
 * GET /api/v2/chimera/entities/pending
 * Get all entities pending approval (Admin only)
 * listPending: Shows content waiting for admin review
 */
router.get("/pending", requireAuth, async (req: Request, res: Response) => {
  try {
    const userId = req.ctx?.userId;
    if (!userId) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.UNAUTHORIZED,
        "Authentication required",
        req,
      );
    }

    // Check if user is admin (use middleware pattern for consistency)
    const { data: profile } = await supabaseAdmin
      .from("profiles")
      .select("role")
      .eq("id", userId)
      .single();

    const isAdmin = profile?.role === "admin" || profile?.role === "system";

    if (!isAdmin) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.FORBIDDEN,
        "Admin access required",
        req,
      );
    }

    // Query pending submissions
    const { data: entities, error } = await supabaseAdmin
      .from("chimera_entities")
      .select(
        "id, key, kind, owner_user_id, visibility, raw_data, created_at, updated_at",
      )
      .eq("visibility", "pending")
      .order("created_at", { ascending: false });

    if (error) {
      console.error(
        "[Chimera Entities] Error fetching pending entities:",
        error,
      );
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        "Failed to fetch pending entities",
        req,
      );
    }

    return sendSuccess(res, entities || [], req);
  } catch (error) {
    console.error("[Chimera Entities] Unexpected error:", error);
    return sendErrorWithStatus(
      res,
      ApiErrorCode.INTERNAL_ERROR,
      "Internal server error",
      req,
    );
  }
});

/**
 * GET /api/v2/chimera/entities/my-creations
 * Get all entities owned by the current user (alias for /)
 */
router.get("/my-creations", (req: Request, res: Response) =>
  entityRead(req, res, (service) =>
    service.list(EntityReadQuerySchema.parse(req.query), "owned"),
  ),
);

/**
 * POST /api/v2/chimera/entities
 * Create a new entity template
 */
router.post(
  "/",
  validateRequest(CreateEntitySchema),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          "Authentication required",
          req,
        );
      }

      // Delegate to Service
      // Service handles: sanitization, world_id strictness, retries, tags
      const entity = await ChimeraEntitiesService.createEntity({
        ...req.body,
        userId,
      });

      return sendSuccess(res, entity, req);
    } catch (error) {
      console.error("[Chimera Entities] Unexpected error:", error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        "Internal server error",
        req,
      );
    }
  },
);

/**
 * GET /api/v2/chimera/entities/:id
 * Get a single entity template
 */
router.get("/:id", (req: Request, res: Response) =>
  entityRead(req, res, (service) =>
    service.find(EntityReadIdSchema.parse(req.params.id)),
  ),
);

/**
 * PUT /api/v2/chimera/entities/:id
 * Update an entity template (owner-only)
 */
router.put(
  "/:id",
  validateRequest(EntityIdParamSchema, "params"),
  validateRequest(UpdateEntitySchema),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          "Authentication required",
          req,
        );
      }

      const { id } = req.params;
      const updateData = req.body;

      // Check ownership and lifecycle state
      const { data: existing, error: checkError } = await supabaseAdmin
        .from("chimera_entities")
        .select("owner_user_id, raw_data, visibility")
        .eq("id", id)
        .single();

      if (checkError) {
        if (checkError.code === "PGRST116") {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.NOT_FOUND,
            "Entity not found",
            req,
          );
        }
        console.error(
          "[Chimera Entities] Error checking ownership:",
          checkError,
        );
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          "Failed to verify ownership",
          req,
        );
      }

      if (existing.owner_user_id !== userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          "You do not have permission to update this entity",
          req,
        );
      }

      // Lifecycle enforcement: Cannot edit published content
      const currentVisibility =
        existing.visibility ||
        (existing.raw_data as any)?.visibility ||
        "private";
      if (currentVisibility === "public" && !updateData.visibility) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          "Cannot edit published content. Please clone to create a new version.",
          req,
        );
      }

      // Delegate to Service
      await ChimeraEntitiesService.updateEntity(id, updateData);

      return sendSuccess(res, { success: true }, req);
    } catch (error) {
      console.error("[Chimera Entities] Unexpected error:", error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        "Internal server error",
        req,
      );
    }
  },
);

/**
 * DELETE /api/v2/chimera/entities/:id
 * Delete an entity template (owner-only)
 */
router.delete(
  "/:id",
  validateRequest(EntityIdParamSchema, "params"),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          "Authentication required",
          req,
        );
      }

      const { id } = req.params;

      // Check ownership
      const { data: existing, error: checkError } = await supabaseAdmin
        .from("chimera_entities")
        .select("owner_user_id")
        .eq("id", id)
        .single();

      if (checkError) {
        if (checkError.code === "PGRST116") {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.NOT_FOUND,
            "Entity not found",
            req,
          );
        }
        console.error(
          "[Chimera Entities] Error checking ownership:",
          checkError,
        );
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          "Failed to verify ownership",
          req,
        );
      }

      if (existing.owner_user_id !== userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          "You do not have permission to delete this entity",
          req,
        );
      }

      // Delete the entity
      const { error: deleteError } = await supabaseAdmin
        .from("chimera_entities")
        .delete()
        .eq("id", id);

      if (deleteError) {
        console.error("[Chimera Entities] Error deleting entity:", deleteError);
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          "Failed to delete entity",
          req,
        );
      }

      return sendSuccess(res, { success: true }, req);
    } catch (error) {
      console.error("[Chimera Entities] Unexpected error:", error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        "Internal server error",
        req,
      );
    }
  },
);

export default router;
