/**
 * @swagger
 * tags:
 *   - name: Chimera V2 Entities
 *     description: User-facing CRUD endpoints for Chimera entity templates
 */

import { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import { requireAuth } from '../middleware/auth.unified.js';
import { validateRequest } from '../middleware/validation.js';
import { sendSuccess, sendErrorWithStatus } from '../utils/response.js';
import { ApiErrorCode } from '@shared';
import { supabaseAdmin } from '../services/supabase.js';

const router = Router();

// Schema for UUID entity ID
const EntityIdParamSchema = z.object({
  id: z.string().uuid(),
});

// All routes require authentication
router.use(requireAuth);

// Zod schemas for validation
const EntityTypeSchema = z.enum(['NPC', 'ITEM', 'FACTION', 'LOCATION']);
const VisibilitySchema = z.enum(['private', 'pending_approval', 'public']);

const CreateEntitySchema = z.object({
  display_name: z.string().min(1).max(200),
  description_short: z.string().max(500).optional().nullable(),
  description_long: z.string().optional().nullable(),
  entity_type: EntityTypeSchema,
  base_state_json: z.record(z.unknown()).default({}),
  tag_names: z.array(z.string()).default([]),
});

const UpdateEntitySchema = z.object({
  display_name: z.string().min(1).max(200).optional(),
  description_short: z.string().max(500).optional().nullable(),
  description_long: z.string().optional().nullable(),
  entity_type: EntityTypeSchema.optional(),
  base_state_json: z.record(z.unknown()).optional(),
  tag_names: z.array(z.string()).optional(),
  visibility: VisibilitySchema.optional(),
}).transform((data) => {
  // Remove empty string values - convert to undefined so they're omitted
  const cleaned: any = { ...data };
  if (cleaned.entity_type === '' || cleaned.entity_type === null) {
    delete cleaned.entity_type;
  }
  if (cleaned.display_name === '' || cleaned.display_name === null) {
    delete cleaned.display_name;
  }
  return cleaned;
});

// Helper function to normalize tag names
function normalizeTagName(tagName: string): string {
  return tagName
    .trim()
    .toUpperCase()
    .replace(/\s+/g, '_')
    .replace(/[^A-Z0-9_]/g, '');
}

// Note: Entity IDs are now UUIDs generated by the database (gen_random_uuid())
// No need for a generateId function - the database will generate UUIDs automatically

/**
 * GET /api/v2/chimera/entities/selectable
 * Returns all public/private entities (for pack selection)
 */
router.get('/selectable', async (req: Request, res: Response) => {
  try {
    const userId = req.ctx?.userId;
    if (!userId) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.UNAUTHORIZED,
        'Authentication required',
        req
      );
    }

    // Get entities that are either public or owned by the user
    const { data: entities, error } = await supabaseAdmin
      .from('chimera_entity_templates')
      .select('id, display_name, entity_type, version, visibility')
      .or(`visibility.eq.public,owner_user_id.eq.${userId}`)
      .order('display_name', { ascending: true });

    if (error) {
      console.error('[Chimera Entities] Error fetching selectable entities:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Failed to fetch entities',
        req
      );
    }

    return sendSuccess(res, entities || [], req);
  } catch (error) {
    console.error('[Chimera Entities] Unexpected error:', error);
    return sendErrorWithStatus(
      res,
      ApiErrorCode.INTERNAL_ERROR,
      'Internal server error',
      req
    );
  }
});

/**
 * GET /api/v2/chimera/entities
 * Get all entities owned by the current user
 */
router.get('/', async (req: Request, res: Response) => {
  try {
    const userId = req.ctx?.userId;
    if (!userId) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.UNAUTHORIZED,
        'Authentication required',
        req
      );
    }

    const { data: entities, error } = await supabaseAdmin
      .from('chimera_entity_templates')
      .select('*')
      .eq('owner_user_id', userId)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('[Chimera Entities] Error fetching user entities:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Failed to fetch entities',
        req
      );
    }

    return sendSuccess(res, entities || [], req);
  } catch (error) {
    console.error('[Chimera Entities] Unexpected error:', error);
    return sendErrorWithStatus(
      res,
      ApiErrorCode.INTERNAL_ERROR,
      'Internal server error',
      req
    );
  }
});

/**
 * GET /api/v2/chimera/entities/my-creations
 * Get all entities owned by the current user (alias for /)
 */
router.get('/my-creations', async (req: Request, res: Response) => {
  try {
    const userId = req.ctx?.userId;
    if (!userId) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.UNAUTHORIZED,
        'Authentication required',
        req
      );
    }

    const { data: entities, error } = await supabaseAdmin
      .from('chimera_entity_templates')
      .select('*')
      .eq('owner_user_id', userId)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('[Chimera Entities] Error fetching user entities:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Failed to fetch entities',
        req
      );
    }

    return sendSuccess(res, entities || [], req);
  } catch (error) {
    console.error('[Chimera Entities] Unexpected error:', error);
    return sendErrorWithStatus(
      res,
      ApiErrorCode.INTERNAL_ERROR,
      'Internal server error',
      req
    );
  }
});

/**
 * POST /api/v2/chimera/entities
 * Create a new entity template
 */
router.post(
  '/',
  validateRequest(CreateEntitySchema),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          'Authentication required',
          req
        );
      }

      const entityData = req.body;

      // Validate base_state_json is valid JSON
      let baseStateJson: Record<string, unknown>;
      try {
        if (typeof entityData.base_state_json === 'string') {
          baseStateJson = JSON.parse(entityData.base_state_json);
        } else {
          baseStateJson = entityData.base_state_json || {};
        }
      } catch (error) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.VALIDATION_FAILED,
          'Invalid JSON in base_state_json',
          req
        );
      }

      // Create the entity - always set visibility to 'private' for new entities
      // Let the database generate the UUID via gen_random_uuid() default
      const { data: entity, error: entityError } = await supabaseAdmin
        .from('chimera_entity_templates')
        .insert({
          owner_user_id: userId,
          display_name: entityData.display_name,
          description_short: entityData.description_short,
          description_long: entityData.description_long,
          entity_type: entityData.entity_type,
          base_state_json: baseStateJson,
          visibility: 'private', // Always private for new entities
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        })
        .select()
        .single();

      if (entityError) {
        console.error('[Chimera Entities] Error creating entity:', entityError);
        // Check for unique constraint violation
        if (entityError.code === '23505') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.CONFLICT,
            'An entity with this name already exists',
            req
          );
        }
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to create entity',
          req
        );
      }

      // Handle tags: normalize, create/get tags, and create links
      if (entityData.tag_names && entityData.tag_names.length > 0) {
        const tagIds: string[] = [];

        for (const tagName of entityData.tag_names) {
          const normalized = normalizeTagName(tagName);
          if (!normalized) continue;

          // Check if tag exists
          const { data: existingTag, error: checkError } = await supabaseAdmin
            .from('chimera_tags')
            .select('id')
            .eq('tag_name', normalized)
            .single();

          let tagId: string;

          // PGRST116 is "not found" which is expected if tag doesn't exist
          if (checkError && checkError.code !== 'PGRST116') {
            console.error('[Chimera Entities] Error checking existing tag:', checkError);
            // Continue to next tag instead of failing entire entity creation
            continue;
          }

          if (existingTag) {
            tagId = existingTag.id;
          } else {
            // Create new tag (unapproved)
            const { data: newTag, error: tagError } = await supabaseAdmin
              .from('chimera_tags')
              .insert({
                tag_name: normalized,
                is_approved: false,
              })
              .select('id')
              .single();

            if (tagError) {
              console.error('[Chimera Entities] Error creating tag:', tagError);
              // Log the full error for debugging
              console.error('[Chimera Entities] Tag creation error details:', JSON.stringify(tagError, null, 2));
              continue;
            }

            if (!newTag || !newTag.id) {
              console.error('[Chimera Entities] Tag created but no ID returned');
              continue;
            }

            tagId = newTag.id;
          }

          tagIds.push(tagId);
        }

        // Create asset tag links
        if (tagIds.length > 0 && entity?.id) {
          const assetTagLinks = tagIds.map((tagId) => ({
            tag_id: tagId,
            asset_id: String(entity.id), // Convert UUID to string for TEXT column
            asset_type: 'entity_template',
          }));

          const { error: linksError } = await supabaseAdmin
            .from('chimera_asset_tags')
            .insert(assetTagLinks);

          if (linksError) {
            console.error('[Chimera Entities] Error creating tag links:', linksError);
            // Continue anyway - entity is created, tags can be fixed later
          }
        }
      }

      return sendSuccess(res, entity, req);
    } catch (error) {
      console.error('[Chimera Entities] Unexpected error:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Internal server error',
        req
      );
    }
  }
);

/**
 * GET /api/v2/chimera/entities/:id
 * Get a single entity template
 */
router.get(
  '/:id',
  validateRequest(EntityIdParamSchema, 'params'),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          'Authentication required',
          req
        );
      }

      const { id } = req.params;

      const { data: entity, error } = await supabaseAdmin
        .from('chimera_entity_templates')
        .select('*')
        .eq('id', id)
        .single();

      if (error) {
        if (error.code === 'PGRST116') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.NOT_FOUND,
            'Entity not found',
            req
          );
        }
        console.error('[Chimera Entities] Error fetching entity:', error);
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to fetch entity',
          req
        );
      }

      // Check ownership or public visibility
      if (entity.owner_user_id !== userId && entity.visibility !== 'public') {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          'You do not have permission to view this entity',
          req
        );
      }

      // Fetch tags
      const { data: assetTags } = await supabaseAdmin
        .from('chimera_asset_tags')
        .select(`
          tag:chimera_tags!tag_id(id, tag_name)
        `)
        .eq('asset_id', id)
        .eq('asset_type', 'entity_template');

      if (assetTags && entity) {
        (entity as any).tags = assetTags
          .map((link: any) => link.tag)
          .filter((tag: any) => tag !== null);
      }

      return sendSuccess(res, entity, req);
    } catch (error) {
      console.error('[Chimera Entities] Unexpected error:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Internal server error',
        req
      );
    }
  }
);

/**
 * PUT /api/v2/chimera/entities/:id
 * Update an entity template (owner-only)
 */
router.put(
  '/:id',
  validateRequest(EntityIdParamSchema, 'params'),
  validateRequest(UpdateEntitySchema),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          'Authentication required',
          req
        );
      }

      const { id } = req.params;
      const updateData = req.body;
      const { tag_names, ...otherUpdateData } = updateData;

      // Check ownership
      const { data: existing, error: checkError } = await supabaseAdmin
        .from('chimera_entity_templates')
        .select('owner_user_id')
        .eq('id', id)
        .single();

      if (checkError) {
        if (checkError.code === 'PGRST116') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.NOT_FOUND,
            'Entity not found',
            req
          );
        }
        console.error('[Chimera Entities] Error checking ownership:', checkError);
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to verify ownership',
          req
        );
      }

      if (existing.owner_user_id !== userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          'You do not have permission to update this entity',
          req
        );
      }

      // Build update payload
      const updatePayload: Record<string, unknown> = {
        updated_at: new Date().toISOString(),
      };

      if (otherUpdateData.display_name !== undefined) {
        updatePayload.display_name = otherUpdateData.display_name;
      }
      if (otherUpdateData.description_short !== undefined) {
        updatePayload.description_short = otherUpdateData.description_short;
      }
      if (otherUpdateData.description_long !== undefined) {
        updatePayload.description_long = otherUpdateData.description_long;
      }
      if (otherUpdateData.entity_type !== undefined) {
        updatePayload.entity_type = otherUpdateData.entity_type;
      }
      if (otherUpdateData.visibility !== undefined) {
        updatePayload.visibility = otherUpdateData.visibility;
      }
      if (otherUpdateData.base_state_json !== undefined) {
        // Validate JSON if it's a string
        let baseStateJson: Record<string, unknown>;
        try {
          if (typeof otherUpdateData.base_state_json === 'string') {
            baseStateJson = JSON.parse(otherUpdateData.base_state_json);
          } else {
            baseStateJson = otherUpdateData.base_state_json;
          }
        } catch (error) {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.VALIDATION_FAILED,
            'Invalid JSON in base_state_json',
            req
          );
        }
        updatePayload.base_state_json = baseStateJson;
      }

      // Update the entity
      const { data: entity, error: updateError } = await supabaseAdmin
        .from('chimera_entity_templates')
        .update(updatePayload)
        .eq('id', id)
        .select()
        .single();

      if (updateError) {
        console.error('[Chimera Entities] Error updating entity:', updateError);
        if (updateError.code === '23505') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.CONFLICT,
            'An entity with this name already exists',
            req
          );
        }
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to update entity',
          req
        );
      }

      // Handle tags if provided
      if (tag_names !== undefined) {
        // Delete existing tag links
        await supabaseAdmin
          .from('chimera_asset_tags')
          .delete()
          .eq('asset_id', id)
          .eq('asset_type', 'entity_template');

        // Create new tag links
        if (tag_names.length > 0) {
          const tagIds: string[] = [];

          for (const tagName of tag_names) {
            const normalized = normalizeTagName(tagName);
            if (!normalized) continue;

            // Check if tag exists
            const { data: existingTag, error: checkError } = await supabaseAdmin
              .from('chimera_tags')
              .select('id')
              .eq('tag_name', normalized)
              .single();

            let tagId: string;

            // PGRST116 is "not found" which is expected if tag doesn't exist
            if (checkError && checkError.code !== 'PGRST116') {
              console.error('[Chimera Entities] Error checking existing tag:', checkError);
              continue;
            }

            if (existingTag) {
              tagId = existingTag.id;
            } else {
              // Create new tag (unapproved)
              const { data: newTag, error: tagError } = await supabaseAdmin
                .from('chimera_tags')
                .insert({
                  tag_name: normalized,
                  is_approved: false,
                })
                .select('id')
                .single();

              if (tagError) {
                console.error('[Chimera Entities] Error creating tag:', tagError);
                continue;
              }

              if (!newTag || !newTag.id) {
                console.error('[Chimera Entities] Tag created but no ID returned');
                continue;
              }

              tagId = newTag.id;
            }

            tagIds.push(tagId);
          }

          // Create asset tag links
          if (tagIds.length > 0) {
            const assetTagLinks = tagIds.map((tagId) => ({
              tag_id: tagId,
              asset_id: String(id), // Convert UUID to string for TEXT column
              asset_type: 'entity_template',
            }));

            const { error: linksError } = await supabaseAdmin
              .from('chimera_asset_tags')
              .insert(assetTagLinks);

            if (linksError) {
              console.error('[Chimera Entities] Error creating tag links:', linksError);
              // Continue anyway - entity is updated, tags can be fixed later
            }
          }
        }
      }

      // Fetch tags for response
      const { data: assetTags } = await supabaseAdmin
        .from('chimera_asset_tags')
        .select(`
          tag:chimera_tags!tag_id(id, tag_name)
        `)
        .eq('asset_id', id)
        .eq('asset_type', 'entity_template');

      if (assetTags && entity) {
        (entity as any).tags = assetTags
          .map((link: any) => link.tag)
          .filter((tag: any) => tag !== null);
      }

      return sendSuccess(res, entity, req);
    } catch (error) {
      console.error('[Chimera Entities] Unexpected error:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Internal server error',
        req
      );
    }
  }
);

/**
 * DELETE /api/v2/chimera/entities/:id
 * Delete an entity template (owner-only)
 */
router.delete(
  '/:id',
  validateRequest(EntityIdParamSchema, 'params'),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          'Authentication required',
          req
        );
      }

      const { id } = req.params;

      // Check ownership
      const { data: existing, error: checkError } = await supabaseAdmin
        .from('chimera_entity_templates')
        .select('owner_user_id')
        .eq('id', id)
        .single();

      if (checkError) {
        if (checkError.code === 'PGRST116') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.NOT_FOUND,
            'Entity not found',
            req
          );
        }
        console.error('[Chimera Entities] Error checking ownership:', checkError);
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to verify ownership',
          req
        );
      }

      if (existing.owner_user_id !== userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          'You do not have permission to delete this entity',
          req
        );
      }

      // Delete the entity
      const { error: deleteError } = await supabaseAdmin
        .from('chimera_entity_templates')
        .delete()
        .eq('id', id);

      if (deleteError) {
        console.error('[Chimera Entities] Error deleting entity:', deleteError);
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to delete entity',
          req
        );
      }

      return sendSuccess(res, { success: true }, req);
    } catch (error) {
      console.error('[Chimera Entities] Unexpected error:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Internal server error',
        req
      );
    }
  }
);

export default router;

