/**
 * @swagger
 * tags:
 *   - name: Chimera V2 Entities
 *     description: User-facing CRUD endpoints for Chimera entity templates
 */

import { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import { requireAuth, requireAdmin } from '../middleware/auth.unified.js';
import { validateRequest } from '../middleware/validation.js';
import { sendSuccess, sendErrorWithStatus } from '../utils/response.js';
import { ApiErrorCode } from '@shared';
import { supabaseAdmin } from '../services/supabase.js';

const router = Router();

// Schema for UUID entity ID
const EntityIdParamSchema = z.object({
  id: z.string().uuid(),
});

// All routes require authentication
router.use(requireAuth);

// Zod schemas for validation
const EntityTypeSchema = z.enum(['NPC', 'ITEM', 'FACTION', 'LOCATION']);
const VisibilitySchema = z.enum(['private', 'pending_approval', 'public']);

const CreateEntitySchema = z.object({
  display_name: z.string().min(1).max(200),
  description_short: z.string().max(500).optional().nullable(),
  description_long: z.string().optional().nullable(),
  entity_type: EntityTypeSchema,
  base_state_json: z.record(z.unknown()).default({}),
  tag_names: z.array(z.string()).default([]),
  images: z.array(z.object({
    id: z.string().optional(),
    url: z.string(),
    role: z.string().optional(),
    label: z.string().optional(),
  })).optional().default([]),
});

const UpdateEntitySchema = z.object({
  display_name: z.string().min(1).max(200).optional(),
  description_short: z.string().max(500).optional().nullable(),
  description_long: z.string().optional().nullable(),
  entity_type: EntityTypeSchema.optional(),
  base_state_json: z.record(z.unknown()).optional(),
  tag_names: z.array(z.string()).optional(),
  visibility: VisibilitySchema.optional(),
  images: z.array(z.object({
    id: z.string().optional(),
    url: z.string(),
    role: z.string().optional(),
    label: z.string().optional(),
  })).optional(),
}).transform((data) => {
  // Remove empty string values - convert to undefined so they're omitted
  const cleaned: any = { ...data };
  if (cleaned.entity_type === '' || cleaned.entity_type === null) {
    delete cleaned.entity_type;
  }
  if (cleaned.display_name === '' || cleaned.display_name === null) {
    delete cleaned.display_name;
  }
  return cleaned;
});

// Helper function to normalize tag names
function normalizeTagName(tagName: string): string {
  return tagName
    .trim()
    .toUpperCase()
    .replace(/\s+/g, '_')
    .replace(/[^A-Z0-9_]/g, '');
}

// Note: Entity IDs are now UUIDs generated by the database (gen_random_uuid())
// No need for a generateId function - the database will generate UUIDs automatically

/**
 * GET /api/v2/chimera/entities/selectable
 * listLibrary: Get all entities available to the user (for Casting Circle)
 * 
 * Pattern: Shows user's items + system items + other users' public items
 * Unified query: owner_user_id = userId OR visibility = 'public'
 */
router.get('/selectable', async (req: Request, res: Response) => {
  try {
    const userId = req.ctx?.userId;
    if (!userId) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.UNAUTHORIZED,
        'Authentication required',
        req
      );
    }

    // listLibrary pattern: User's content OR public content (includes system)
    const { data: entities, error } = await supabaseAdmin
      .from('chimera_entities')
      .select('id, key, kind, owner_user_id, visibility, raw_data, created_at, updated_at')
      .or(`owner_user_id.eq.${userId},visibility.eq.public`)
      .order('created_at', { ascending: false });
    
    // Map to expected format (use SQL visibility column, fallback to raw_data for backward compatibility)
    const mappedEntities = (entities || []).map((entity: any) => {
      const rawData = entity.raw_data || {};
      return {
        id: entity.id,
        key: entity.key,
        kind: entity.kind,
        owner_user_id: entity.owner_user_id,
        raw_data: entity.raw_data,
        display_name: rawData.display_name || rawData.identity?.name || entity.key,
        entity_type: entity.kind,
        version: rawData.version || 1,
        visibility: entity.visibility || rawData.visibility || 'private', // Use SQL column first
        created_at: entity.created_at,
        updated_at: entity.updated_at,
      };
    }).sort((a: any, b: any) => (a.display_name || '').localeCompare(b.display_name || ''));

    if (error) {
      console.error('[Chimera Entities] Error fetching selectable entities:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Failed to fetch entities',
        req
      );
    }

    return sendSuccess(res, entities || [], req);
  } catch (error) {
    console.error('[Chimera Entities] Unexpected error:', error);
    return sendErrorWithStatus(
      res,
      ApiErrorCode.INTERNAL_ERROR,
      'Internal server error',
      req
    );
  }
});

/**
 * GET /api/v2/chimera/entities
 * Get all entities owned by the current user
 */
router.get('/', async (req: Request, res: Response) => {
  try {
    const userId = req.ctx?.userId;
    if (!userId) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.UNAUTHORIZED,
        'Authentication required',
        req
      );
    }

    // Get entities owned by user (Hybrid Schema: use owner_user_id SQL column)
    const { data: entities, error } = await supabaseAdmin
      .from('chimera_entities')
      .select('id, key, kind, owner_user_id, raw_data, created_at, updated_at')
      .eq('owner_user_id', userId)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('[Chimera Entities] Error fetching user entities:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Failed to fetch entities',
        req
      );
    }

    return sendSuccess(res, entities || [], req);
  } catch (error) {
    console.error('[Chimera Entities] Unexpected error:', error);
    return sendErrorWithStatus(
      res,
      ApiErrorCode.INTERNAL_ERROR,
      'Internal server error',
      req
    );
  }
});

/**
 * GET /api/v2/chimera/entities/pending
 * Get all entities pending approval (Admin only)
 * listPending: Shows content waiting for admin review
 */
router.get('/pending', requireAuth, async (req: Request, res: Response) => {
  try {
    const userId = req.ctx?.userId;
    if (!userId) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.UNAUTHORIZED,
        'Authentication required',
        req
      );
    }

    // Check if user is admin (use middleware pattern for consistency)
    const { data: profile } = await supabaseAdmin
      .from('profiles')
      .select('role')
      .eq('id', userId)
      .single();
    
    const isAdmin = profile?.role === 'admin' || profile?.role === 'system';
    
    if (!isAdmin) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.FORBIDDEN,
        'Admin access required',
        req
      );
    }

    // Query pending submissions
    const { data: entities, error } = await supabaseAdmin
      .from('chimera_entities')
      .select('id, key, kind, owner_user_id, visibility, raw_data, created_at, updated_at')
      .eq('visibility', 'pending')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('[Chimera Entities] Error fetching pending entities:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Failed to fetch pending entities',
        req
      );
    }

    return sendSuccess(res, entities || [], req);
  } catch (error) {
    console.error('[Chimera Entities] Unexpected error:', error);
    return sendErrorWithStatus(
      res,
      ApiErrorCode.INTERNAL_ERROR,
      'Internal server error',
      req
    );
  }
});

/**
 * GET /api/v2/chimera/entities/my-creations
 * Get all entities owned by the current user (alias for /)
 */
router.get('/my-creations', async (req: Request, res: Response) => {
  try {
    const userId = req.ctx?.userId;
    if (!userId) {
      return sendErrorWithStatus(
        res,
        ApiErrorCode.UNAUTHORIZED,
        'Authentication required',
        req
      );
    }

    const { data: entities, error } = await supabaseAdmin
      .from('chimera_entities')
      .select('*')
      .eq('owner_user_id', userId)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('[Chimera Entities] Error fetching user entities:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Failed to fetch entities',
        req
      );
    }

    return sendSuccess(res, entities || [], req);
  } catch (error) {
    console.error('[Chimera Entities] Unexpected error:', error);
    return sendErrorWithStatus(
      res,
      ApiErrorCode.INTERNAL_ERROR,
      'Internal server error',
      req
    );
  }
});

/**
 * POST /api/v2/chimera/entities
 * Create a new entity template
 */
router.post(
  '/',
  validateRequest(CreateEntitySchema),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          'Authentication required',
          req
        );
      }

      const entityData = req.body;

      // Validate base_state_json is valid JSON
      let baseStateJson: Record<string, unknown>;
      try {
        if (typeof entityData.base_state_json === 'string') {
          baseStateJson = JSON.parse(entityData.base_state_json);
        } else {
          baseStateJson = entityData.base_state_json || {};
        }
      } catch (error) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.VALIDATION_FAILED,
          'Invalid JSON in base_state_json',
          req
        );
      }

      // Create the entity (Hybrid Schema: key/kind SQL columns + raw_data JSONB + owner_user_id)
      // Generate key from display_name (normalized)
      const key = entityData.display_name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-');
      const kind = entityData.entity_type.toLowerCase() as 'npc' | 'item' | 'location' | 'faction' | 'creature';
      
      // Store full entity definition in raw_data JSONB
      const rawData = {
        display_name: entityData.display_name,
        description_short: entityData.description_short,
        description_long: entityData.description_long,
        entity_type: entityData.entity_type,
        base_state_json: baseStateJson,
        images: entityData.images || [],
        visibility: 'private', // Always private for new entities
        owner_user_id: userId,
        version: 1,
      };
      
      const { data: entity, error: entityError } = await supabaseAdmin
        .from('chimera_entities')
        .insert({
          key,
          kind,
          owner_user_id: userId, // SQL column for ownership tracking
          raw_data: rawData, // JSONB containing full entity definition
        })
        .select('id, key, kind, owner_user_id, raw_data, created_at, updated_at')
        .single();

      if (entityError) {
        console.error('[Chimera Entities] Error creating entity:', entityError);
        // Check for unique constraint violation
        if (entityError.code === '23505') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.CONFLICT,
            'An entity with this name already exists',
            req
          );
        }
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to create entity',
          req
        );
      }

      // Handle tags: normalize, create/get tags, and create links
      if (entityData.tag_names && entityData.tag_names.length > 0) {
        const tagIds: string[] = [];

        for (const tagName of entityData.tag_names) {
          const normalized = normalizeTagName(tagName);
          if (!normalized) continue;

          // Check if tag exists
          const { data: existingTag, error: checkError } = await supabaseAdmin
            .from('chimera_tags')
            .select('id')
            .eq('tag_name', normalized)
            .single();

          let tagId: string;

          // PGRST116 is "not found" which is expected if tag doesn't exist
          if (checkError && checkError.code !== 'PGRST116') {
            console.error('[Chimera Entities] Error checking existing tag:', checkError);
            // Continue to next tag instead of failing entire entity creation
            continue;
          }

          if (existingTag) {
            tagId = existingTag.id;
          } else {
            // Create new tag (unapproved)
            const { data: newTag, error: tagError } = await supabaseAdmin
              .from('chimera_tags')
              .insert({
                tag_name: normalized,
                is_approved: false,
              })
              .select('id')
              .single();

            if (tagError) {
              console.error('[Chimera Entities] Error creating tag:', tagError);
              // Log the full error for debugging
              console.error('[Chimera Entities] Tag creation error details:', JSON.stringify(tagError, null, 2));
              continue;
            }

            if (!newTag || !newTag.id) {
              console.error('[Chimera Entities] Tag created but no ID returned');
              continue;
            }

            tagId = newTag.id;
          }

          tagIds.push(tagId);
        }

        // Create asset tag links
        if (tagIds.length > 0 && entity?.id) {
          const assetTagLinks = tagIds.map((tagId) => ({
            tag_id: tagId,
            asset_id: String(entity.id), // Convert UUID to string for TEXT column
            asset_type: 'entity_template',
          }));

          const { error: linksError } = await supabaseAdmin
            .from('chimera_asset_tags')
            .insert(assetTagLinks);

          if (linksError) {
            console.error('[Chimera Entities] Error creating tag links:', linksError);
            // Continue anyway - entity is created, tags can be fixed later
          }
        }
      }

      return sendSuccess(res, entity, req);
    } catch (error) {
      console.error('[Chimera Entities] Unexpected error:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Internal server error',
        req
      );
    }
  }
);

/**
 * GET /api/v2/chimera/entities/:id
 * Get a single entity template
 */
router.get(
  '/:id',
  validateRequest(EntityIdParamSchema, 'params'),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          'Authentication required',
          req
        );
      }

      const { id } = req.params;

      const { data: entity, error } = await supabaseAdmin
        .from('chimera_entities')
        .select('*')
        .eq('id', id)
        .single();

      if (error) {
        if (error.code === 'PGRST116') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.NOT_FOUND,
            'Entity not found',
            req
          );
        }
        console.error('[Chimera Entities] Error fetching entity:', error);
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to fetch entity',
          req
        );
      }

      // Check ownership or public visibility
      if (entity.owner_user_id !== userId && entity.visibility !== 'public') {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          'You do not have permission to view this entity',
          req
        );
      }

      // Fetch tags
      const { data: assetTags } = await supabaseAdmin
        .from('chimera_asset_tags')
        .select(`
          tag:chimera_tags!tag_id(id, tag_name)
        `)
        .eq('asset_id', id)
        .eq('asset_type', 'entity_template');

      if (assetTags && entity) {
        (entity as any).tags = assetTags
          .map((link: any) => link.tag)
          .filter((tag: any) => tag !== null);
      }

      // Extract base_state_json from raw_data (handle both new and legacy formats)
      const rawData = entity.raw_data || {};
      let baseStateJson: Record<string, unknown> = {};
      
      if (rawData.base_state_json) {
        // New format: base_state_json is nested
        baseStateJson = rawData.base_state_json;
      } else {
        // Legacy format: extract state by excluding known metadata fields
        const metadataFields = [
          'display_name',
          'name', // Legacy name field
          'description_short',
          'description', // Legacy description field
          'description_long',
          'entity_type',
          'type', // Legacy type field
          'images',
          'visibility',
          'version',
          'owner_user_id',
          'identity', // Legacy identity object
        ];
        
        baseStateJson = { ...rawData };
        // Remove metadata fields to get just the state
        for (const field of metadataFields) {
          delete baseStateJson[field];
        }
        
        // If identity exists, merge its contents into base_state_json
        if (rawData.identity && typeof rawData.identity === 'object') {
          baseStateJson = { ...baseStateJson, ...(rawData.identity as Record<string, unknown>) };
        }
      }

      // Transform response to include extracted fields
      const transformedEntity = {
        ...entity,
        display_name: rawData.display_name || rawData.name || (rawData.identity && typeof rawData.identity === 'object' ? (rawData.identity as any).name : null) || entity.key,
        description_short: rawData.description_short || rawData.description || null,
        entity_type: rawData.entity_type || rawData.type || entity.kind?.toUpperCase(),
        base_state_json: baseStateJson,
        images: rawData.images || [],
      };

      return sendSuccess(res, transformedEntity, req);
    } catch (error) {
      console.error('[Chimera Entities] Unexpected error:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Internal server error',
        req
      );
    }
  }
);

/**
 * PUT /api/v2/chimera/entities/:id
 * Update an entity template (owner-only)
 */
router.put(
  '/:id',
  validateRequest(EntityIdParamSchema, 'params'),
  validateRequest(UpdateEntitySchema),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          'Authentication required',
          req
        );
      }

      const { id } = req.params;
      const updateData = req.body;
      const { tag_names, ...otherUpdateData } = updateData;

      // Check ownership and lifecycle state
      const { data: existing, error: checkError } = await supabaseAdmin
        .from('chimera_entities')
        .select('owner_user_id, raw_data, visibility')
        .eq('id', id)
        .single();

      if (checkError) {
        if (checkError.code === 'PGRST116') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.NOT_FOUND,
            'Entity not found',
            req
          );
        }
        console.error('[Chimera Entities] Error checking ownership:', checkError);
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to verify ownership',
          req
        );
      }

      if (existing.owner_user_id !== userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          'You do not have permission to update this entity',
          req
        );
      }

      // Lifecycle enforcement: Cannot edit published content
      // Use SQL visibility column (primary source of truth)
      const currentVisibility = existing.visibility || (existing.raw_data as any)?.visibility || 'private';
      if (currentVisibility === 'public' && !updateData.visibility) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          'Cannot edit published content. Please clone to create a new version.',
          req
        );
      }

      // Track publishing: Detect if visibility is changing to 'public'
      const isPublishing = updateData.visibility === 'public' && currentVisibility !== 'public';
      
      // Check if user is authorized to publish directly (admin or verified creator)
      const { data: profile } = await supabaseAdmin
        .from('profiles')
        .select('role, is_verified_creator')
        .eq('id', userId)
        .single();
      const isAdmin = profile?.role === 'admin' || profile?.role === 'system';
      const isVerifiedCreator = profile?.is_verified_creator === true;
      const canPublishDirectly = isAdmin || isVerifiedCreator;
      
      // Gatekeeper Logic: Force 'pending' if user tries to publish but isn't authorized
      let finalVisibility = updateData.visibility;
      let wasCoercedToPending = false;
      if (updateData.visibility === 'public' && !canPublishDirectly) {
        finalVisibility = 'pending';
        wasCoercedToPending = true;
        console.log(`[Chimera Entities] User ${userId} attempted to publish but is not authorized. Setting visibility to 'pending'.`);
      }

      // Build update payload
      const updatePayload: Record<string, unknown> = {
        updated_at: new Date().toISOString(),
      };

      // Initialize updatedRawData from existing raw_data
      const existingRawData = existing.raw_data || {};
      const updatedRawData = { ...existingRawData };

      if (otherUpdateData.display_name !== undefined) {
        updatePayload.display_name = otherUpdateData.display_name;
        updatedRawData.display_name = otherUpdateData.display_name;
      }
      if (otherUpdateData.description_short !== undefined) {
        updatePayload.description_short = otherUpdateData.description_short;
        updatedRawData.description_short = otherUpdateData.description_short;
      }
      if (otherUpdateData.description_long !== undefined) {
        updatedRawData.description_long = otherUpdateData.description_long;
      }
      if (otherUpdateData.entity_type !== undefined) {
        updatePayload.entity_type = otherUpdateData.entity_type;
        updatedRawData.entity_type = otherUpdateData.entity_type;
      }
      if (otherUpdateData.visibility !== undefined) {
        updatePayload.visibility = finalVisibility; // Use coerced visibility if needed
        updatedRawData.visibility = finalVisibility;
        
        // Track publishing: Set published_by and published_at when visibility changes to 'public'
        // Only set if actually publishing (not coerced to pending)
        if (isPublishing && canPublishDirectly) {
          updatePayload.published_by = userId;
          updatePayload.published_at = new Date().toISOString();
          
          // Allow admins to set is_official flag when publishing
          if (updateData.is_official !== undefined && isAdmin) {
            updatePayload.is_official = updateData.is_official;
          }
        }
      }
      if (otherUpdateData.base_state_json !== undefined) {
        // Validate JSON if it's a string
        let baseStateJson: Record<string, unknown>;
        try {
          if (typeof otherUpdateData.base_state_json === 'string') {
            baseStateJson = JSON.parse(otherUpdateData.base_state_json);
          } else {
            baseStateJson = otherUpdateData.base_state_json;
          }
        } catch (error) {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.VALIDATION_FAILED,
            'Invalid JSON in base_state_json',
            req
          );
        }
        updatedRawData.base_state_json = baseStateJson;
      }

      if (otherUpdateData.images !== undefined) {
        updatedRawData.images = otherUpdateData.images;
      }

      // Update raw_data with all changes
      updatePayload.raw_data = updatedRawData;

      // Update the entity
      const { data: entity, error: updateError } = await supabaseAdmin
        .from('chimera_entities')
        .update(updatePayload)
        .eq('id', id)
        .select()
        .single();

      if (updateError) {
        console.error('[Chimera Entities] Error updating entity:', updateError);
        if (updateError.code === '23505') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.CONFLICT,
            'An entity with this name already exists',
            req
          );
        }
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to update entity',
          req
        );
      }

      // Handle tags if provided
      if (tag_names !== undefined) {
        // Delete existing tag links
        await supabaseAdmin
          .from('chimera_asset_tags')
          .delete()
          .eq('asset_id', id)
          .eq('asset_type', 'entity_template');

        // Create new tag links
        if (tag_names.length > 0) {
          const tagIds: string[] = [];

          for (const tagName of tag_names) {
            const normalized = normalizeTagName(tagName);
            if (!normalized) continue;

            // Check if tag exists
            const { data: existingTag, error: checkError } = await supabaseAdmin
              .from('chimera_tags')
              .select('id')
              .eq('tag_name', normalized)
              .single();

            let tagId: string;

            // PGRST116 is "not found" which is expected if tag doesn't exist
            if (checkError && checkError.code !== 'PGRST116') {
              console.error('[Chimera Entities] Error checking existing tag:', checkError);
              continue;
            }

            if (existingTag) {
              tagId = existingTag.id;
            } else {
              // Create new tag (unapproved)
              const { data: newTag, error: tagError } = await supabaseAdmin
                .from('chimera_tags')
                .insert({
                  tag_name: normalized,
                  is_approved: false,
                })
                .select('id')
                .single();

              if (tagError) {
                console.error('[Chimera Entities] Error creating tag:', tagError);
                continue;
              }

              if (!newTag || !newTag.id) {
                console.error('[Chimera Entities] Tag created but no ID returned');
                continue;
              }

              tagId = newTag.id;
            }

            tagIds.push(tagId);
          }

          // Create asset tag links
          if (tagIds.length > 0) {
            const assetTagLinks = tagIds.map((tagId) => ({
              tag_id: tagId,
              asset_id: String(id), // Convert UUID to string for TEXT column
              asset_type: 'entity_template',
            }));

            const { error: linksError } = await supabaseAdmin
              .from('chimera_asset_tags')
              .insert(assetTagLinks);

            if (linksError) {
              console.error('[Chimera Entities] Error creating tag links:', linksError);
              // Continue anyway - entity is updated, tags can be fixed later
            }
          }
        }
      }

      // Fetch tags for response
      const { data: assetTags } = await supabaseAdmin
        .from('chimera_asset_tags')
        .select(`
          tag:chimera_tags!tag_id(id, tag_name)
        `)
        .eq('asset_id', id)
        .eq('asset_type', 'entity_template');

      if (assetTags && entity) {
        (entity as any).tags = assetTags
          .map((link: any) => link.tag)
          .filter((tag: any) => tag !== null);
      }

      // If visibility was coerced to pending, include a message
      if (wasCoercedToPending) {
        return sendSuccess(
          res, 
          { 
            ...entity, 
            _message: 'Content submitted for approval. Visibility set to "pending" as you are not a verified creator.' 
          }, 
          req
        );
      }

      return sendSuccess(res, entity, req);
    } catch (error) {
      console.error('[Chimera Entities] Unexpected error:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Internal server error',
        req
      );
    }
  }
);

/**
 * DELETE /api/v2/chimera/entities/:id
 * Delete an entity template (owner-only)
 */
router.delete(
  '/:id',
  validateRequest(EntityIdParamSchema, 'params'),
  async (req: Request, res: Response) => {
    try {
      const userId = req.ctx?.userId;
      if (!userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.UNAUTHORIZED,
          'Authentication required',
          req
        );
      }

      const { id } = req.params;

      // Check ownership
      const { data: existing, error: checkError } = await supabaseAdmin
        .from('chimera_entities')
        .select('owner_user_id')
        .eq('id', id)
        .single();

      if (checkError) {
        if (checkError.code === 'PGRST116') {
          return sendErrorWithStatus(
            res,
            ApiErrorCode.NOT_FOUND,
            'Entity not found',
            req
          );
        }
        console.error('[Chimera Entities] Error checking ownership:', checkError);
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to verify ownership',
          req
        );
      }

      if (existing.owner_user_id !== userId) {
        return sendErrorWithStatus(
          res,
          ApiErrorCode.FORBIDDEN,
          'You do not have permission to delete this entity',
          req
        );
      }

      // Delete the entity
      const { error: deleteError } = await supabaseAdmin
        .from('chimera_entities')
        .delete()
        .eq('id', id);

      if (deleteError) {
        console.error('[Chimera Entities] Error deleting entity:', deleteError);
        return sendErrorWithStatus(
          res,
          ApiErrorCode.INTERNAL_ERROR,
          'Failed to delete entity',
          req
        );
      }

      return sendSuccess(res, { success: true }, req);
    } catch (error) {
      console.error('[Chimera Entities] Unexpected error:', error);
      return sendErrorWithStatus(
        res,
        ApiErrorCode.INTERNAL_ERROR,
        'Internal server error',
        req
      );
    }
  }
);

export default router;

