-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- mechanics_conditions: 8 row(s)
set search_path to public, extensions;
insert into public.mechanics_conditions
select * from jsonb_populate_recordset(null::public.mechanics_conditions, $seed$[
{"id":"bleeding","stacking":"add","cap":3,"cleanse_keys":["heal","bandage"],"tick_hooks":{"resource_deltas":[{"key":"hp","delta":-2}]},"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"blessed","stacking":"none","cap":null,"cleanse_keys":["curse","dispel"],"tick_hooks":{"resource_deltas":[{"key":"mana","delta":1}]},"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"exhausted","stacking":"add","cap":3,"cleanse_keys":["rest","energy_boost"],"tick_hooks":{"resource_deltas":[{"key":"energy","delta":-1}]},"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"frightened","stacking":"none","cap":null,"cleanse_keys":["courage","calm"],"tick_hooks":{"resource_deltas":[{"key":"stress","delta":1}]},"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"guarded","stacking":"none","cap":null,"cleanse_keys":["dispel","break_guard"],"tick_hooks":{},"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"inspired","stacking":"none","cap":null,"cleanse_keys":["fear","dispel"],"tick_hooks":{"resource_deltas":[{"key":"mana","delta":2}]},"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"poisoned","stacking":"add","cap":5,"cleanse_keys":["antidote","cure_poison"],"tick_hooks":{"resource_deltas":[{"key":"hp","delta":-1}]},"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"stunned","stacking":"none","cap":null,"cleanse_keys":["cure_stun"],"tick_hooks":{},"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"}
]$seed$::jsonb)
on conflict do nothing;
