-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- injection_map: 1 row(s)
set search_path to public, extensions;
insert into public.injection_map
select * from jsonb_populate_recordset(null::public.injection_map, $seed$[
{"id":"default","doc":{"build":{"contract":{"from":"core_contracts.active.doc.contract"},"input_text":{"from":"input.text"},"world_meta":{"from":"worlds[{session.world_ref}].doc"},"core_scales":{"from":"core_contracts.active.doc.core.scales"},"meta_locale":{"from":"session.locale"},"npcs_active":{"from":"npcs.active"},"player_data":{"from":"player_profiles[{session.player_id}].doc"},"core_budgets":{"from":"core_contracts.active.doc.core.budgets","fallback":{"ifMissing":{"input_max_tokens":6000,"output_max_tokens":1200}}},"core_ruleset":{"from":"core_rulesets[{session.meta.ruleset_ref}].doc.ruleset"},"meta_turn_id":{"from":"session.turn_id"},"adventure_meta":{"from":"adventures[{session.adventure_ref}].doc"},"game_state_hot":{"from":"game_states[{session.session_id}].hot"},"game_state_cold":{"from":"game_states[{session.session_id}].cold"},"game_state_warm":{"from":"game_states[{session.session_id}].warm"},"core_acts_catalog":{"from":"core_contracts.active.doc.core.acts_catalog"},"meta_is_first_turn":{"from":"session.is_first_turn"}}},"created_at":"2025-10-19T20:58:55.841539+00:00","updated_at":"2025-10-19T20:58:55.841539+00:00"}
]$seed$::jsonb)
on conflict do nothing;
