-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- dialogue_config: 1 row(s)
set search_path to public, extensions;
insert into public.dialogue_config
select * from jsonb_populate_recordset(null::public.dialogue_config, $seed$[
{"id":"default","module_mode":"full","max_tokens":220,"max_candidates":3,"romance_enabled":true,"romance_min_trust":65,"romance_cooldown_turns":3,"safety_explicit_block":true,"created_at":"2025-10-17T21:51:42.337977+00:00","updated_at":"2025-10-17T21:51:42.337977+00:00"}
]$seed$::jsonb)
on conflict do nothing;
