-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- ai_config: 4 row(s)
set search_path to public, extensions;
insert into public.ai_config
select * from jsonb_populate_recordset(null::public.ai_config, $seed$[
{"key":"active_model","value":{"value":"PRIMARY_AI_MODEL"},"updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"max_tokens_in","value":{"value":4096},"updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"max_tokens_out","value":{"value":1024},"updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"prompt_schema_version","value":{"value":"1.0.0"},"updated_at":"2025-10-01T20:17:41.383443+00:00"}
]$seed$::jsonb)
on conflict do nothing;
