-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- mechanics_skills: 15 row(s)
set search_path to public, extensions;
insert into public.mechanics_skills
select * from jsonb_populate_recordset(null::public.mechanics_skills, $seed$[
{"id":"acrobatics","description":"Balance and agility","baseline":8,"tags":["physical","combat"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"athletics","description":"Physical feats and climbing","baseline":8,"tags":["physical","combat"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"charisma","description":"Force of personality","baseline":10,"tags":["social","magic"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"constitution","description":"Endurance and health","baseline":10,"tags":["physical","survival"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"deception","description":"Lying and misdirection","baseline":8,"tags":["social","magic"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"dexterity","description":"Agility and reflexes","baseline":10,"tags":["physical","combat"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"insight","description":"Reading people and situations","baseline":8,"tags":["mental","social"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"intelligence","description":"Reasoning and memory","baseline":10,"tags":["mental","magic"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"intimidation","description":"Inspiring fear","baseline":8,"tags":["social","combat"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"investigation","description":"Searching and analyzing","baseline":8,"tags":["mental","social"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"perception","description":"Noticing details","baseline":8,"tags":["mental","survival"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"persuasion","description":"Convincing others","baseline":8,"tags":["social","magic"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"stealth","description":"Hiding and sneaking","baseline":8,"tags":["physical","social"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"strength","description":"Physical power and muscle","baseline":10,"tags":["physical","combat"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"wisdom","description":"Perception and insight","baseline":10,"tags":["mental","survival"],"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"}
]$seed$::jsonb)
on conflict do nothing;
