-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- localization_glossary: 3 row(s)
set search_path to public, extensions;
insert into public.localization_glossary
select * from jsonb_populate_recordset(null::public.localization_glossary, $seed$[
{"id":"41e325b4-7a65-4d41-8752-40fc3d3da7e2","locale":"en-US","entries":[],"hash":"default-en","created_at":"2025-10-17T16:53:01.432792+00:00","updated_at":"2025-10-17T16:53:01.432792+00:00"},
{"id":"d2940dcf-967f-4e5c-910f-7a7a60fdb2db","locale":"es-ES","entries":[],"hash":"default-es","created_at":"2025-10-17T16:53:01.432792+00:00","updated_at":"2025-10-17T16:53:01.432792+00:00"},
{"id":"4355551d-384a-40b9-825e-4054cb34864b","locale":"fr-FR","entries":[],"hash":"default-fr","created_at":"2025-10-17T16:53:01.432792+00:00","updated_at":"2025-10-17T16:53:01.432792+00:00"}
]$seed$::jsonb)
on conflict do nothing;
