-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- pricing_config: 6 row(s)
set search_path to public, extensions;
insert into public.pricing_config
select * from jsonb_populate_recordset(null::public.pricing_config, $seed$[
{"key":"conversion_rates","value":{"value":{"relic":500,"shard":10,"crystal":100}},"updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"guest_daily_regen","value":{"value":0},"updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"guest_starter_casting_stones","value":{"value":15},"updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"stone_packs","value":{"value":[{"id":"starter","name":"Starter Pack","bonus":{"relic":1,"shard":10,"crystal":5},"price":999,"stones":{"relic":10,"shard":100,"crystal":50},"currency":"USD","description":"Perfect for new adventurers to get started"},{"id":"adventurer","name":"Adventurer Pack","bonus":{"relic":2,"shard":25,"crystal":12},"price":1999,"stones":{"relic":25,"shard":250,"crystal":125},"currency":"USD","description":"Great value for regular players"},{"id":"hero","name":"Hero Pack","bonus":{"relic":7,"shard":75,"crystal":37},"price":4999,"stones":{"relic":75,"shard":750,"crystal":375},"currency":"USD","description":"For serious adventurers who need more stones"},{"id":"legend","name":"Legend Pack","bonus":{"relic":20,"shard":200,"crystal":100},"price":9999,"stones":{"relic":200,"shard":2000,"crystal":1000},"currency":"USD","description":"The ultimate pack for legendary adventures"}]},"updated_at":"2025-10-03T01:59:40.989256+00:00"},
{"key":"turn_cost_by_world","value":{"value":{}},"updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"turn_cost_default","value":{"value":2},"updated_at":"2025-10-01T20:17:41.383443+00:00"}
]$seed$::jsonb)
on conflict do nothing;
