-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- slots: 5 row(s)
set search_path to public, extensions;
insert into public.slots
select * from jsonb_populate_recordset(null::public.slots, $seed$[
{"id":"70a76a81-a900-4db3-8186-55d83798df6b","type":"npc","name":"bio","description":"NPC biographical information","max_len":400,"priority":1,"created_at":"2025-11-08T22:57:15.197817+00:00","updated_at":"2025-11-08T22:57:15.656+00:00","must_keep":false,"min_chars":null},
{"id":"ff8bcb84-58a8-439b-bbde-69f5ff82b42c","type":"ruleset","name":"choice_style","description":"Style guide for presenting choices to players","max_len":300,"priority":2,"created_at":"2025-11-08T22:57:15.069322+00:00","updated_at":"2025-11-08T22:57:15.531+00:00","must_keep":false,"min_chars":null},
{"id":"f930bb8d-263d-40e3-bfbd-5a8efeeff8c1","type":"npc","name":"persona","description":"NPC personality and behavioral traits","max_len":300,"priority":2,"created_at":"2025-11-08T22:57:15.274367+00:00","updated_at":"2025-11-08T22:57:15.744+00:00","must_keep":false,"min_chars":null},
{"id":"3addbf80-67b7-45b2-b9c6-c733730bd021","type":"ruleset","name":"principles","description":"Core narrative principles for the ruleset","max_len":1000,"priority":1,"created_at":"2025-11-08T22:57:14.995958+00:00","updated_at":"2025-11-08T22:57:15.459+00:00","must_keep":false,"min_chars":null},
{"id":"89d7c56e-90bd-4907-a6c8-6df6419622f8","type":"world","name":"tone","description":"World narrative tone and atmosphere","max_len":500,"priority":1,"created_at":"2025-11-08T22:57:14.922701+00:00","updated_at":"2025-11-08T22:57:15.376+00:00","must_keep":false,"min_chars":null}
]$seed$::jsonb)
on conflict do nothing;
