-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- quest_graphs: 1 row(s)
set search_path to public, extensions;
insert into public.quest_graphs
select * from jsonb_populate_recordset(null::public.quest_graphs, $seed$[
{"id":"95f4c2f8-4ff6-40da-8116-70e2eb2a864d","adventure_ref":"whispercross","version":"1.0.0","doc":{"edges":[{"to":"beat.trust_test","from":"beat.intro","guard":[{"status":"complete","objective":"meet_kiera"}]}],"nodes":[{"id":"beat.intro","hint":"Try a calm greeting or show a harmless token.","type":"beat","on_fail":[{"act":"FLAG_SET","key":"intro_failed","val":true}],"enter_if":[{"op":"ne","val":true,"flag":"met_kiera"}],"synopsis":"Moonlit glade, first contact with Kiera.","on_success":[{"id":"meet_kiera","act":"OBJECTIVE_UPDATE","status":"complete"}]},{"id":"beat.trust_test","hint":"Show kindness or help others in need.","type":"objective","on_fail":[{"act":"FLAG_SET","key":"trust_failed","val":true}],"enter_if":[{"status":"complete","objective":"meet_kiera"}],"synopsis":"Prove your worth to Kiera through actions.","on_success":[{"id":"gain_trust","act":"OBJECTIVE_UPDATE","status":"complete"}]}],"start":"beat.intro","graph_id":"adv.whispercross.v1.g1"},"hash":"test-hash-123","created_at":"2025-10-17T19:32:24.765786+00:00","updated_at":"2025-10-17T19:32:24.765786+00:00"}
]$seed$::jsonb)
on conflict do nothing;
