-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- app_config: 6 row(s)
set search_path to public, extensions;
insert into public.app_config
select * from jsonb_populate_recordset(null::public.app_config, $seed$[
{"key":"allow_async_turn_fallback","value":{"value":true},"type":"boolean","updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"cookie_ttl_days","value":{"value":60},"type":"number","updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"drifter_enabled","value":{"value":true},"type":"boolean","updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"guest_cookie_issue_rate_limit_per_hour","value":{"value":10},"type":"number","updated_at":"2025-10-03T01:58:02.897832+00:00"},
{"key":"idempotency_required","value":{"value":true},"type":"boolean","updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"telemetry_sample_rate","value":{"value":1},"type":"number","updated_at":"2025-10-01T20:17:41.383443+00:00"}
]$seed$::jsonb)
on conflict do nothing;
