-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- localization_rules: 3 row(s)
set search_path to public, extensions;
insert into public.localization_rules
select * from jsonb_populate_recordset(null::public.localization_rules, $seed$[
{"locale":"en-US","policy":{"formal_you":false,"sentence_caps":120,"choice_label_max":48,"forbidden_phrases":[]},"created_at":"2025-10-17T16:53:01.432792+00:00","updated_at":"2025-10-17T16:53:01.432792+00:00"},
{"locale":"es-ES","policy":{"formal_you":true,"sentence_caps":130,"choice_label_max":48,"forbidden_phrases":[]},"created_at":"2025-10-17T16:53:01.432792+00:00","updated_at":"2025-10-17T16:53:01.432792+00:00"},
{"locale":"fr-FR","policy":{"formal_you":true,"sentence_caps":140,"choice_label_max":48,"forbidden_phrases":[]},"created_at":"2025-10-17T16:53:01.432792+00:00","updated_at":"2025-10-17T16:53:01.432792+00:00"}
]$seed$::jsonb)
on conflict do nothing;
