-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- chimera_asset_tags: 9 row(s) — only rows whose asset is in this seed
set search_path to public, extensions;
insert into public.chimera_asset_tags
select * from jsonb_populate_recordset(null::public.chimera_asset_tags, $seed$[
{"tag_id":"35a6abc0-bf79-49dd-b276-b81095709c03","asset_id":"789dbece-3bc9-4080-82ce-31b47139fbb5","asset_type":"entity","created_at":"2025-12-05T19:40:15.575391+00:00"},
{"tag_id":"35a6abc0-bf79-49dd-b276-b81095709c03","asset_id":"b3de4b0a-a879-43cf-8256-2153a5ff97a9","asset_type":"world","created_at":"2025-12-03T19:57:45.752566+00:00"},
{"tag_id":"4b1efa05-c3b0-4bb9-9910-9fc1f51bbf11","asset_id":"789dbece-3bc9-4080-82ce-31b47139fbb5","asset_type":"entity","created_at":"2025-12-05T19:40:15.575391+00:00"},
{"tag_id":"53e1efd7-93d6-4c5a-9583-1fb4fb9c478c","asset_id":"b3de4b0a-a879-43cf-8256-2153a5ff97a9","asset_type":"world","created_at":"2025-12-03T19:57:45.752566+00:00"},
{"tag_id":"66495ef8-d589-467c-91f3-df0d5b1231fc","asset_id":"789dbece-3bc9-4080-82ce-31b47139fbb5","asset_type":"entity","created_at":"2025-12-05T19:40:15.575391+00:00"},
{"tag_id":"763e382b-0dac-40df-b525-eb9182980d55","asset_id":"b3de4b0a-a879-43cf-8256-2153a5ff97a9","asset_type":"world","created_at":"2025-12-03T19:57:45.752566+00:00"},
{"tag_id":"bbec656a-f54c-44f9-b886-ae8929dfd004","asset_id":"b3de4b0a-a879-43cf-8256-2153a5ff97a9","asset_type":"world","created_at":"2025-12-03T19:57:45.752566+00:00"},
{"tag_id":"c4e7c66f-4cde-4b6d-a90d-453b97ed9f7b","asset_id":"789dbece-3bc9-4080-82ce-31b47139fbb5","asset_type":"entity","created_at":"2025-12-05T19:40:15.575391+00:00"},
{"tag_id":"e5794812-d0c3-4e19-b8c2-3e0d81e30ad0","asset_id":"b3de4b0a-a879-43cf-8256-2153a5ff97a9","asset_type":"world","created_at":"2025-12-03T19:57:45.752566+00:00"}
]$seed$::jsonb)
on conflict do nothing;
