-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- mechanics_resources: 6 row(s)
set search_path to public, extensions;
insert into public.mechanics_resources
select * from jsonb_populate_recordset(null::public.mechanics_resources, $seed$[
{"id":"energy","min_value":0,"max_value":100,"regen_per_tick":2,"decay_per_tick":0,"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"favor","min_value":0,"max_value":100,"regen_per_tick":0,"decay_per_tick":0,"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"hp","min_value":0,"max_value":100,"regen_per_tick":0,"decay_per_tick":0,"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"mana","min_value":0,"max_value":100,"regen_per_tick":1,"decay_per_tick":0,"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"stamina","min_value":0,"max_value":100,"regen_per_tick":1,"decay_per_tick":0,"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"},
{"id":"stress","min_value":0,"max_value":100,"regen_per_tick":0,"decay_per_tick":1,"created_at":"2025-10-17T19:32:35.21922+00:00","updated_at":"2025-10-17T19:32:35.21922+00:00"}
]$seed$::jsonb)
on conflict do nothing;
