-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- feature_flags: 4 row(s)
set search_path to public, extensions;
insert into public.feature_flags
select * from jsonb_populate_recordset(null::public.feature_flags, $seed$[
{"key":"drifter_onboarding","enabled":true,"payload":{},"updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"stones_show_guest_pill","enabled":true,"payload":{},"updated_at":"2025-10-01T20:17:41.383443+00:00"},
{"key":"telemetry_enabled","enabled":true,"payload":{},"updated_at":"2025-10-03T01:58:02.897832+00:00"},
{"key":"ws_push_enabled","enabled":false,"payload":{},"updated_at":"2025-10-01T20:17:41.383443+00:00"}
]$seed$::jsonb)
on conflict do nothing;
