-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- config_meta: 1 row(s)
set search_path to public, extensions;
insert into public.config_meta
select * from jsonb_populate_recordset(null::public.config_meta, $seed$[
{"id":true,"version":1,"updated_at":"2025-10-01T20:17:33.710915+00:00"}
]$seed$::jsonb)
on conflict do nothing;
