-- GENERATED by supabase/scripts/export-hosted-base.mjs from hosted stone-caster-2 (obfadjnywufemhhhcxiy). Do not hand-edit.
-- chimera_world_ruleset_link: 0 row(s)
set search_path to public, extensions;
-- (no rows)
