-- StoneCaster canonical local baseline (3/6): foreign keys and indexes.
-- Redundant duplicate indexes present on hosted (same columns as a unique constraint / another index) are omitted.
set search_path to public, extensions;

-- ---------- foreign keys ----------
alter table public.ai_audit_logs add constraint ai_audit_logs_turn_id_fkey foreign key (turn_id) references public.chimera_turns(id) on delete set null;
alter table public.auth_ledger add constraint auth_ledger_canonical_group_id_fkey foreign key (canonical_group_id) references public.cookie_groups(id) on delete cascade;
alter table public.auth_ledger add constraint auth_ledger_source_group_id_fkey foreign key (source_group_id) references public.cookie_groups(id) on delete set null;
alter table public.auth_ledger add constraint auth_ledger_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.author_drafts add constraint author_drafts_updated_by_fkey foreign key (updated_by) references auth.users(id);
alter table public.author_workspace_members add constraint author_workspace_members_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.author_workspace_members add constraint author_workspace_members_workspace_id_fkey foreign key (workspace_id) references public.author_workspaces(id) on delete cascade;
alter table public.author_workspaces add constraint author_workspaces_created_by_fkey foreign key (created_by) references auth.users(id);
alter table public.chimera_asset_tags add constraint chimera_asset_tags_tag_id_fkey foreign key (tag_id) references public.chimera_tags(id);
alter table public.chimera_assets add constraint chimera_assets_owner_id_fkey foreign key (owner_id) references auth.users(id);
alter table public.chimera_compiled_stories add constraint chimera_compiled_stories_story_id_fkey foreign key (story_id) references public.chimera_stories(id) on delete cascade;
alter table public.chimera_content_pack_entity_links add constraint chimera_content_pack_entity_links_pack_id_fkey foreign key (pack_id) references public.chimera_content_packs(id);
alter table public.chimera_content_pack_lore_links add constraint fk_pack_lore_links foreign key (pack_id) references public.chimera_content_packs(id) on delete cascade;
alter table public.chimera_content_pack_ruleset_links add constraint chimera_content_pack_ruleset_links_pack_id_fkey foreign key (pack_id) references public.chimera_content_packs(id);
alter table public.chimera_content_packs add constraint chimera_content_packs_owner_user_id_fkey foreign key (owner_user_id) references auth.users(id);
alter table public.chimera_entities add constraint chimera_entities_owner_user_id_fkey foreign key (owner_user_id) references auth.users(id);
alter table public.chimera_entities add constraint chimera_entities_world_id_fkey foreign key (world_id) references public.chimera_worlds(id);
alter table public.chimera_lore add constraint chimera_lore_entity_id_fkey foreign key (entity_id) references public.chimera_entities(id) on delete cascade;
alter table public.chimera_lore add constraint chimera_lore_owner_user_id_fkey foreign key (owner_user_id) references auth.users(id);
alter table public.chimera_lore add constraint chimera_lore_story_id_fkey foreign key (story_id) references public.chimera_stories(id) on delete cascade;
alter table public.chimera_lore add constraint chimera_lore_world_id_fkey foreign key (world_id) references public.chimera_worlds(id) on delete cascade;
alter table public.chimera_pack_dependencies add constraint chimera_pack_dependencies_depends_on_pack_id_fkey foreign key (depends_on_pack_id) references public.chimera_content_packs(id);
alter table public.chimera_pack_dependencies add constraint chimera_pack_dependencies_pack_id_fkey foreign key (pack_id) references public.chimera_content_packs(id);
alter table public.chimera_player_characters add constraint chimera_player_characters_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.chimera_player_characters add constraint chimera_player_characters_world_id_fkey foreign key (world_id) references public.chimera_worlds(id);
alter table public.chimera_stories add constraint chimera_stories_current_compiled_id_fkey foreign key (current_compiled_id) references public.chimera_compiled_stories(id) on delete set null;
alter table public.chimera_stories add constraint chimera_stories_owner_user_id_fkey foreign key (owner_user_id) references auth.users(id);
alter table public.chimera_stories add constraint chimera_stories_protagonist_id_fkey foreign key (protagonist_id) references public.chimera_entities(id);
alter table public.chimera_stories add constraint chimera_stories_world_id_fkey foreign key (world_id) references public.chimera_worlds(id) on delete set null;
alter table public.chimera_story_compiled_ruleset add constraint chimera_story_compiled_ruleset_story_id_fkey foreign key (story_id) references public.chimera_stories(id);
alter table public.chimera_story_content_pack_links add constraint chimera_story_content_pack_links_pack_id_fkey foreign key (pack_id) references public.chimera_content_packs(id);
alter table public.chimera_story_content_pack_links add constraint chimera_story_content_pack_links_story_id_fkey foreign key (story_id) references public.chimera_stories(id);
alter table public.chimera_story_entity_links add constraint chimera_story_entity_links_story_id_fkey foreign key (story_id) references public.chimera_stories(id);
alter table public.chimera_story_links add constraint chimera_story_links_story_id_fkey foreign key (story_id) references public.chimera_stories(id);
alter table public.chimera_turns add constraint chimera_turns_game_state_id_fkey foreign key (game_state_id) references public.chimera_game_states(id) on delete cascade;
alter table public.cookie_group_members add constraint cookie_group_members_group_id_fkey foreign key (group_id) references public.cookie_groups(id) on delete cascade;
alter table public.cookie_groups add constraint cookie_groups_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.creator_namespaces add constraint creator_namespaces_creator_id_fkey foreign key (creator_id) references public.creators(creator_id) on delete cascade;
alter table public.csrf_tokens add constraint csrf_tokens_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.experiment_variations add constraint experiment_variations_experiment_key_fkey foreign key (experiment_key) references public.experiments(key) on delete cascade;
alter table public.media_assets add constraint media_assets_owner_user_id_fkey foreign key (owner_user_id) references auth.users(id) on delete cascade;
alter table public.media_links add constraint media_links_v2_media_id_fkey foreign key (media_id) references public.media_assets(id) on delete cascade;
alter table public.payment_sessions add constraint payment_sessions_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.profiles add constraint profiles_approved_by_fkey foreign key (approved_by) references auth.users(id);
alter table public.profiles add constraint profiles_id_fkey foreign key (id) references auth.users(id) on delete cascade;
alter table public.prompts add constraint prompts_created_by_fkey foreign key (created_by) references auth.users(id) on delete set null;
alter table public.publish_history add constraint publish_history_from_draft_id_fkey foreign key (from_draft_id) references public.author_drafts(id);
alter table public.publish_history add constraint publish_history_published_by_fkey foreign key (published_by) references auth.users(id);
alter table public.quest_graph_indexes add constraint quest_graph_indexes_graph_id_fkey foreign key (graph_id) references public.quest_graphs(id) on delete cascade;
alter table public.telemetry_events add constraint telemetry_events_user_id_fkey foreign key (user_id) references auth.users(id) on delete set null;
alter table public.user_profiles add constraint user_profiles_auth_user_id_fkey foreign key (auth_user_id) references auth.users(id) on delete cascade;
alter table public.user_profiles add constraint user_profiles_cookie_group_id_fkey foreign key (cookie_group_id) references public.cookie_groups(id) on delete set null;

-- ---------- indexes ----------
create index if not exists ar_created_idx on public.access_requests (created_at);
create index if not exists ar_email_idx on public.access_requests (lower(email));
create index if not exists ar_status_idx on public.access_requests (status);
create index if not exists ar_user_idx on public.access_requests (user_id);
create index if not exists idx_ai_audit_logs_turn on public.ai_audit_logs (turn_id);
create index if not exists idx_analytics_events_experiment on public.analytics_events (experiment_key, variation_key, ts);
create index if not exists idx_analytics_events_session on public.analytics_events (session_id, ts);
create index if not exists idx_analytics_events_ts on public.analytics_events (ts);
create index if not exists idx_analytics_events_world on public.analytics_events (world_ref, ts);
create index if not exists idx_auth_ledger_created_at on public.auth_ledger (created_at);
create index if not exists idx_auth_ledger_guest_cookie_id on public.auth_ledger (guest_cookie_id);
create index if not exists idx_auth_ledger_link_merge on public.auth_ledger (type, user_id, guest_cookie_id) where (type = 'LINK_MERGE');
create index if not exists idx_auth_ledger_type on public.auth_ledger (type);
create index if not exists idx_auth_ledger_user_id on public.auth_ledger (user_id);
create index if not exists idx_author_drafts_doc_type_ref on public.author_drafts (doc_type, doc_ref);
create index if not exists idx_author_drafts_updated_at on public.author_drafts (updated_at);
create index if not exists idx_author_drafts_updated_by on public.author_drafts (updated_by);
create index if not exists idx_author_workspace_members_user_id on public.author_workspace_members (user_id);
create index if not exists idx_author_workspaces_created_by on public.author_workspaces (created_by);
create index if not exists idx_chimera_assets_owner_id on public.chimera_assets (owner_id);
create index if not exists idx_chimera_assets_url on public.chimera_assets (url);
create index if not exists idx_chimera_content_pack_lore_links_lore_template_id on public.chimera_content_pack_lore_links (lore_template_id);
create index if not exists idx_chimera_entities_entity_type on public.chimera_entities (entity_type);
create index if not exists idx_chimera_entities_owner on public.chimera_entities (owner_user_id);
create index if not exists idx_chimera_entities_raw_data on public.chimera_entities using gin (raw_data);
create index if not exists idx_chimera_entities_visibility on public.chimera_entities (visibility);
create index if not exists idx_chimera_entities_world_id on public.chimera_entities (world_id);
create index if not exists idx_entities_official on public.chimera_entities (is_official);
create index if not exists idx_chimera_game_states_created_at on public.chimera_game_states (created_at desc);
create index if not exists idx_chimera_game_states_mechanical on public.chimera_game_states using gin (mechanical_state);
create index if not exists idx_chimera_game_states_player_id on public.chimera_game_states (player_id);
create index if not exists idx_chimera_game_states_story_id on public.chimera_game_states (story_id);
create index if not exists idx_chimera_instances_v3_compiled_story_id on public.chimera_instances_v3 (compiled_story_id);
create index if not exists idx_chimera_instances_v3_current_state on public.chimera_instances_v3 using gin (current_state);
create index if not exists idx_chimera_instances_v3_status on public.chimera_instances_v3 (status);
create index if not exists idx_chimera_instances_v3_user_id on public.chimera_instances_v3 (user_id);
create index if not exists idx_chimera_lore_embedding on public.chimera_lore using ivfflat (embedding vector_cosine_ops) with (lists = '100') where (embedding is not null);
create index if not exists idx_chimera_lore_fragment on public.chimera_lore using gin (fragment);
create index if not exists idx_chimera_lore_keywords on public.chimera_lore using gin (keywords);
create index if not exists idx_chimera_lore_visibility on public.chimera_lore (visibility);
create index if not exists idx_lore_entity on public.chimera_lore (entity_id);
create index if not exists idx_lore_owner on public.chimera_lore (owner_user_id);
create index if not exists idx_lore_story on public.chimera_lore (story_id);
create index if not exists idx_lore_world_id on public.chimera_lore (world_id);
create index if not exists idx_chimera_player_characters_user_id on public.chimera_player_characters (user_id);
create index if not exists idx_chimera_player_characters_world_id on public.chimera_player_characters (world_id);
create index if not exists idx_chimera_ruleset_templates_category on public.chimera_ruleset_templates (ui_category);
create index if not exists idx_chimera_ruleset_templates_definition on public.chimera_ruleset_templates using gin (definition);
create index if not exists idx_chimera_ruleset_templates_dependencies on public.chimera_ruleset_templates using gin (dependencies);
create index if not exists idx_chimera_ruleset_templates_exclusion_group on public.chimera_ruleset_templates (exclusion_group);
create index if not exists idx_chimera_stories_configuration on public.chimera_stories using gin (configuration);
create index if not exists idx_chimera_stories_entity_ids on public.chimera_stories using gin (entity_ids);
create index if not exists idx_chimera_stories_owner_user_id on public.chimera_stories (owner_user_id);
create index if not exists idx_chimera_stories_visibility on public.chimera_stories (visibility);
create index if not exists idx_chimera_stories_world_id on public.chimera_stories (world_id) where (world_id is not null);
create index if not exists idx_chimera_story_entity_links_entity_template_id on public.chimera_story_entity_links (entity_template_id);
create index if not exists idx_chimera_story_links_ruleset_template_id on public.chimera_story_links (ruleset_template_id);
create index if not exists idx_chimera_turns_lookup on public.chimera_turns (game_state_id, turn_index);
create index if not exists idx_chimera_world_ruleset_link_ruleset_template_id on public.chimera_world_ruleset_link (ruleset_template_id);
create index if not exists idx_chimera_world_ruleset_link_world_id on public.chimera_world_ruleset_link (world_id);
create index if not exists idx_chimera_worlds_character_schema on public.chimera_worlds using gin (character_schema_contributions);
create index if not exists idx_chimera_worlds_definition on public.chimera_worlds using gin (definition);
create index if not exists idx_chimera_worlds_genre on public.chimera_worlds (genre);
create index if not exists idx_chimera_worlds_genre_tags on public.chimera_worlds using gin (genre_tags);
create index if not exists idx_chimera_worlds_owner_id on public.chimera_worlds (owner_id);
create index if not exists idx_chimera_worlds_owner_user_id on public.chimera_worlds (owner_user_id) where (owner_user_id is not null);
create index if not exists idx_chimera_worlds_setting on public.chimera_worlds (setting);
create index if not exists idx_chimera_worlds_tags on public.chimera_worlds using gin (tags);
create index if not exists idx_worlds_official on public.chimera_worlds (is_official);
create index if not exists idx_worlds_visibility on public.chimera_worlds (visibility);
create unique index if not exists idx_chimera_worlds_slug on public.chimera_worlds (slug);
create index if not exists idx_compiled_stories_active on public.chimera_compiled_stories (story_id, is_active);
create index if not exists idx_compiled_stories_config_interpreter on public.chimera_compiled_stories using gin (config_interpreter);
create index if not exists idx_compiled_stories_config_mechanics on public.chimera_compiled_stories using gin (config_mechanics);
create index if not exists idx_compiled_stories_config_narrator on public.chimera_compiled_stories using gin (config_narrator);
create index if not exists idx_compiled_stories_config_ui on public.chimera_compiled_stories using gin (config_ui);
create index if not exists idx_compiled_stories_entity_ids on public.chimera_compiled_stories using gin (entity_ids);
create index if not exists idx_compiled_stories_ruleset_ids on public.chimera_compiled_stories using gin (ruleset_ids);
create index if not exists idx_cookie_group_members_group_id on public.cookie_group_members (group_id);
create index if not exists idx_cookie_group_members_last_seen on public.cookie_group_members (last_seen_at);
create index if not exists idx_cookie_issue_requests_created_at on public.cookie_issue_requests (created_at);
create index if not exists idx_cookie_issue_requests_ip_address on public.cookie_issue_requests (ip_address);
create index if not exists idx_creator_namespaces_creator_id on public.creator_namespaces (creator_id);
create index if not exists idx_csrf_tokens_expires_at on public.csrf_tokens (expires_at);
create index if not exists idx_csrf_tokens_token on public.csrf_tokens (token);
create index if not exists idx_csrf_tokens_user_id on public.csrf_tokens (user_id);
create index if not exists idx_dialogue_graphs_adventure_ref on public.dialogue_graphs (adventure_ref);
create index if not exists idx_dialogue_graphs_world_ref on public.dialogue_graphs (world_ref);
create index if not exists idx_idempotency_keys_created_at on public.idempotency_keys (created_at);
create index if not exists idx_idempotency_keys_lookup on public.idempotency_keys (key, owner_id, game_id, operation);
create index if not exists idx_localization_packs_doc_ref on public.localization_packs (doc_ref);
create index if not exists idx_localization_packs_locale on public.localization_packs (locale);
create index if not exists idx_mechanics_skills_tags on public.mechanics_skills using gin (tags);
create index if not exists idx_media_assets_created_at on public.media_assets (created_at);
create index if not exists idx_media_assets_owner on public.media_assets (owner_user_id);
create index if not exists idx_media_assets_status on public.media_assets (status);
create index if not exists idx_media_assets_visibility on public.media_assets (visibility);
create index if not exists idx_media_links_npc on public.media_links (npc_id, sort_order) where (npc_id is not null);
create index if not exists idx_media_links_story on public.media_links (story_id, sort_order) where (story_id is not null);
create index if not exists idx_media_links_world on public.media_links (world_id, sort_order) where (world_id is not null);
create unique index if not exists media_links_entity_media_unique on public.media_links (coalesce(world_id, story_id, (npc_id)::text), media_id);
create index if not exists idx_npc_personalities_npc_adventure on public.npc_personalities (npc_ref, adventure_ref);
create index if not exists idx_npc_personalities_npc_world on public.npc_personalities (npc_ref, world_ref);
create index if not exists idx_payment_sessions_status on public.payment_sessions (status);
create index if not exists idx_payment_sessions_user_id on public.payment_sessions (user_id);
create index if not exists idx_premade_characters_active on public.premade_characters (is_active) where (is_active = true);
create index if not exists idx_premade_characters_world_id on public.premade_characters (world_id);
create index if not exists idx_premade_characters_world_slug on public.premade_characters (world_slug);
create index if not exists idx_profiles_role on public.profiles (role);
create index if not exists idx_profiles_verified_creator on public.profiles (is_verified_creator) where (is_verified_creator = true);
create index if not exists idx_prompts_active on public.prompts (active) where (active = true);
create index if not exists idx_prompts_hash on public.prompts (hash);
create index if not exists idx_prompts_layer_sort on public.prompts (layer, sort_order) where (active = true);
create index if not exists idx_prompts_scene on public.prompts (scene_id) where (active = true and scene_id is not null);
create index if not exists idx_prompts_slug_scope on public.prompts (slug, scope);
create index if not exists idx_prompts_turn_stage on public.prompts (turn_stage) where (active = true);
create index if not exists idx_prompts_world_adventure on public.prompts (world_slug, adventure_slug) where (active = true);
create index if not exists idx_publish_history_doc_type_ref on public.publish_history (doc_type, doc_ref);
create index if not exists idx_quest_graph_indexes_graph on public.quest_graph_indexes (graph_id);
create index if not exists idx_quest_graphs_adventure on public.quest_graphs (adventure_ref);
create index if not exists idx_slots_type on public.slots (type);
create index if not exists idx_snapshots_session_id on public.snapshots (session_id);
create index if not exists idx_telemetry_events_cookie_id on public.telemetry_events (cookie_id);
create index if not exists idx_telemetry_events_created_at on public.telemetry_events (created_at);
create index if not exists idx_telemetry_events_name on public.telemetry_events (name);
create index if not exists idx_telemetry_events_trace_id on public.telemetry_events (trace_id);
create index if not exists idx_telemetry_events_user_id on public.telemetry_events (user_id);
create index if not exists idx_translation_cache_langs on public.translation_cache (src_lang, dst_lang);
create index if not exists idx_turn_analytics_turn_id on public.turn_analytics (turn_id);
create index if not exists idx_turn_metrics_story_created on public.turn_metrics (story_id, created_at desc);
create index if not exists idx_turn_wal_applied on public.turn_wal (applied);
create index if not exists idx_user_profiles_role on public.user_profiles (role);
create unique index if not exists idx_user_profiles_creator_slug_unique on public.user_profiles (creator_slug) where (creator_slug is not null);
