name: API Documentation Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/src/routes/**'
      - 'backend/src/config/swagger.ts'
      - 'backend/scripts/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/src/routes/**'
      - 'backend/src/config/swagger.ts'
      - 'backend/scripts/**'

jobs:
  validate-api-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Build backend
      working-directory: ./backend
      run: npm run build
      
    - name: Validate API documentation
      working-directory: ./backend
      run: npm run docs:validate
      
    - name: Generate OpenAPI specification
      working-directory: ./backend
      run: npm run docs:spec
      
    - name: Upload API specification
      uses: actions/upload-artifact@v4
      with:
        name: api-specification
        path: backend/api-spec.json
        retention-days: 30
        
    - name: Comment PR with API changes
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          try {
            const specPath = path.join(process.cwd(), 'backend', 'api-spec.json');
            if (fs.existsSync(specPath)) {
              const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
              const endpointCount = Object.keys(spec.paths || {}).length;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 📚 API Documentation Status
                
                ✅ **API Documentation Validated**
                📊 **Endpoints Documented**: ${endpointCount}
                📄 **OpenAPI Spec**: Generated and attached
                
                The API documentation has been validated and is up-to-date. All routes are properly documented in Swagger.`
              });
            }
          } catch (error) {
            console.log('Could not create PR comment:', error.message);
          }

  generate-missing-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Generate missing documentation
      working-directory: ./backend
      run: npm run docs:generate
      
    - name: Update API contract
      working-directory: ./backend
      run: npm run docs:contract
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add backend/src/routes/ docs/API_CONTRACT.md
        git diff --staged --quiet || git commit -m "docs: auto-generate missing API documentation"
        git push
